/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.codename1.uikit.cleanmodern;



import com.codename1.components.SpanLabel;
import com.codename1.io.CharArrayReader;
import com.codename1.io.ConnectionRequest;
import com.codename1.io.JSONParser;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.util.Resources;
import com.codename1.io.NetworkEvent;
import com.codename1.io.NetworkManager;
import com.codename1.ui.Button;
import com.codename1.ui.Container;
import com.codename1.ui.TextField;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.spinner.Picker;
import com.codename1.ui.util.UIBuilder;
import java.io.IOException;
import java.util.List;
import java.util.Map;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class login  {

    private Form current;
    private Resources theme;
     Container ct ;
    
public login (Resources theme){
                    UIBuilder.registerCustomComponent("Picker",Picker.class);

        UIBuilder uib = new UIBuilder();
Form f = new Form("Join My Ride", BoxLayout.y());

      SpanLabel sp = new SpanLabel();
      SpanLabel sp1 = new SpanLabel();
      SpanLabel sp2 = new SpanLabel();
      SpanLabel sp3 = new SpanLabel();
      
        TextField t = new TextField("saharghorch", "UserName");
      
        TextField t1 = new TextField("saharsahar", "Mot De passe", 20, TextField.PASSWORD);
                t.setSingleLineTextArea(false);
        t1.setSingleLineTextArea(false);
        f.add(sp);
        f.add(sp1);
        f.add(sp2);
        f.add(t);
        f.add(t1);
 
        Button B = new Button("Log In");
        Button Bt = new Button("Annuler");
        Button b = new Button("crée un compte");
        f.add(B);
        f.add(Bt);
        f.add(b);
   
        b.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent evt) {
                        Inscription IN = new Inscription(theme); 
                        IN.show();
                        }
                    });
        
     

       B.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
             ConnectionRequest con = new ConnectionRequest();
                String name = t.getText();
                String pswd = t1.getText();
               
              
                
                con.setUrl("http://localhost/PIDEVMobile/GestionForum/login.php?username="+name+"&password="+pswd);
               
                con.addResponseListener(new ActionListener<NetworkEvent>() {
                    @Override
                    public void actionPerformed(NetworkEvent evt) {
                        
                         try {
                    String json=new String(con.getResponseData());
                      JSONParser j = new JSONParser();
                              
                    Map<String, Object> users = j.parseJSON(new CharArrayReader(json.toCharArray())); 
                              
                    if(users.get("password").equals("0")) 
                        {
                          Dialog.show("Erreur d'authentification", "Verifier votre Nom d'utilisateur ou mot de passe!!", "OK", "Annuler");

                         }
                    else {
                            Curentuser c =new Curentuser();
                            c.setCurrent(users.get("username").toString());
                            c.setCurrentId(Integer.parseInt(users.get("id").toString()));
                            publications pubs = new publications(theme);
                            pubs.getL().show();
                            System.out.println(c.getCurrentId());
                            System.out.println("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
                    }
                    
                } catch (IOException ex) {
                }   
                 }
                });
                     NetworkManager.getInstance().addToQueue(con);
                      
            }
            
        });
      
        f.show();
        
    }
public void show(){
     
 
 }

}


