package controller;

import entity.*;
import com.codename1.db.Cursor;
import com.codename1.db.Database;
import com.codename1.db.Row;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Button;
import com.codename1.ui.Command;
import com.codename1.ui.Container;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.util.UIBuilder;
import java.io.IOException;
import java.util.ArrayList;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class directionsController {

    Database db;
    Boolean exist;

    UIBuilder uib;

    ArrayList<Direction> directions = new ArrayList<>();

    public ArrayList<Direction> getDirections() throws IOException {
        Database db = Database.openOrCreate("piweb");
        try {
            Cursor c = db.executeQuery("select city,log,lat from cities");

            while (c.next()) {
                Row r = c.getRow();
                Direction direction = new Direction(r.getString(1), r.getDouble(2), r.getDouble(3));
                directions.add(direction);
            }

        } catch (IOException ex) {
            //Logger.getLogger(MyApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
        return directions;
    }

}
