# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    authentication.handler.login_success_handler:
        class:  Pidev\GestionTrajetsBundle\Security\LoginSuccessHandler
        arguments:  ['@router', '@security.authorization_checker']

    app.form.registration:
        class: Pidev\GestionTrajetsBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }